spring:
  application:
    name: healthcare
  data:
    mongodb:
      database: patientsDB
      port: 27017
      host: localhost
    neo4j:
      database: neo4j
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: momen@1234

  influxdb:
    url: http://localhost:8086
    token: wZPA1Q4-00rgA57p9AVyrJCohrT65URVNEeszKk2AszAeBEazw_VHGZW9DfGBz7i8QVAv3lCu_p4kyUChlRRjQ==
    org: healthcare
    bucket: patient_measurements
    retention-policy: 30d

  redis:
    host: localhost
    port: 6379
server:
  port: 8081

