spring:
  data:
    mongodb:
      uri: "mongodb://localhost:27018,localhost:27017/patientsDB?replicaSet=shard01&readPreference=primaryPreferred&retryWrites=true&w=majority"
    redis:
      sentinel:
        master: mymaster
        nodes:
          - 127.0.0.1:26379
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: momen@1234
  influxdb:
    url: http://localhost:8086
    token: wZPA1Q4-00rgA57p9AVyrJCohrT65URVNEeszKk2AszAeBEazw_VHGZW9DfGBz7i8QVAv3lCu_p4kyUChlRRjQ==
    org: healthcare
    bucket: patient_measurements

server:
  port: 8081
